apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}-nginx
        customer: {{ .Values.customerId }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
