apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-ping
spec:
  selector:
    app: {{ .Values.applicationName }}-ping
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
